controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_student:
    path: /affiche
    controller: App\Controller\StudentController::affiche

ajax_search:
    path: /search
    defaults:  
        _controller: 'App\Controller\ReclamationController::searchAction'
