#index:
#    path: /
#    controller: App\Controller\DefaultController::index

rendezvous_calendar:
    path: /rendezvous-calendar/{medecinId}
    controller: App\Controller\RendezvousController::calendar
