<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPa9yMh4\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPa9yMh4/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPa9yMh4.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPa9yMh4\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPa9yMh4\App_KernelDevDebugContainer([
    'container.build_hash' => 'Pa9yMh4',
    'container.build_id' => '1ffaf9ef',
    'container.build_time' => 1709638738,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPa9yMh4');
