<?php

namespace ContainerPa9yMh4;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_CKpHUNeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.CKpHUNe' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.CKpHUNe'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'replyRepository' => ['privates', 'App\\Repository\\ReplyRepository', 'getReplyRepositoryService', true],
        ], [
            'replyRepository' => 'App\\Repository\\ReplyRepository',
        ]);
    }
}
