<?php

namespace ContainerPa9yMh4;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_WS8B5XyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.WS8B5Xy' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.WS8B5Xy'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'mailer' => ['privates', 'mailer.mailer', 'getMailer_MailerService', true],
            'managerRegistry' => ['services', 'doctrine', 'getDoctrineService', false],
            'reservationserviceRepository' => ['privates', 'App\\Repository\\ReservationserviceRepository', 'getReservationserviceRepositoryService', true],
        ], [
            'mailer' => '?',
            'managerRegistry' => '?',
            'reservationserviceRepository' => 'App\\Repository\\ReservationserviceRepository',
        ]);
    }
}
