<?php

namespace ContainerPa9yMh4;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_V41lLHVService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.v41lLHV' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.v41lLHV'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'flashBag' => ['privates', 'session.flash_bag', 'getSession_FlashBagService', true],
            'managerRegistry' => ['services', 'doctrine', 'getDoctrineService', false],
            'reservationserviceRepository' => ['privates', 'App\\Repository\\ReservationserviceRepository', 'getReservationserviceRepositoryService', true],
        ], [
            'flashBag' => '?',
            'managerRegistry' => '?',
            'reservationserviceRepository' => 'App\\Repository\\ReservationserviceRepository',
        ]);
    }
}
