<?php

namespace ContainerPa9yMh4;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_JfiSqc5Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.jfiSqc5' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.jfiSqc5'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'doctorRepository' => ['privates', 'App\\Repository\\MedecinRepository', 'getMedecinRepositoryService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'doctorRepository' => 'App\\Repository\\MedecinRepository',
            'entityManager' => '?',
        ]);
    }
}
