<?php

namespace ContainerPa9yMh4;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_WVVQOnqService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.wVVQOnq' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.wVVQOnq'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'idevent' => ['privates', '.errored..service_locator.wVVQOnq.App\\Entity\\Evenement', NULL, 'Cannot autowire service ".service_locator.wVVQOnq": it references class "App\\Entity\\Evenement" but no such service exists.'],
            'mailer' => ['privates', 'App\\Service\\MailerService', 'getMailerServiceService', true],
        ], [
            'entityManager' => '?',
            'idevent' => 'App\\Entity\\Evenement',
            'mailer' => 'App\\Service\\MailerService',
        ]);
    }
}
